-- HeyMarket schema for Supabase SQL Editor
-- Run once in: Supabase Dashboard → SQL → New query → Run
-- Matches Backend/app/models.py

-- ============================================================
-- 0. Clean reset (optional — only if re-running from scratch)
-- ============================================================
-- DROP TABLE IF EXISTS reviews CASCADE;
-- DROP TABLE IF EXISTS system_notifications CASCADE;
-- DROP TABLE IF EXISTS blocklist CASCADE;
-- DROP TABLE IF EXISTS safety_reports CASCADE;
-- DROP TABLE IF EXISTS user_settings CASCADE;
-- DROP TABLE IF EXISTS payout_methods CASCADE;
-- DROP TABLE IF EXISTS payment_methods CASCADE;
-- DROP TABLE IF EXISTS addresses CASCADE;
-- DROP TABLE IF EXISTS messages CASCADE;
-- DROP TABLE IF EXISTS conversations CASCADE;
-- DROP TABLE IF EXISTS coupons CASCADE;
-- DROP TABLE IF EXISTS follows CASCADE;
-- DROP TABLE IF EXISTS view_history CASCADE;
-- DROP TABLE IF EXISTS favorites CASCADE;
-- DROP TABLE IF EXISTS orders CASCADE;
-- DROP TABLE IF EXISTS listings CASCADE;
-- DROP TABLE IF EXISTS refresh_tokens CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;

-- ============================================================
-- 1. Core tables
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    id              VARCHAR(36) PRIMARY KEY,
    nickname        VARCHAR(50) NOT NULL,
    -- Nullable: OAuth (Google/Apple/WeChat) users have no phone at sign-up.
    phone           VARCHAR(20) UNIQUE,
    email           VARCHAR(255),
    password_hash   VARCHAR(255) NOT NULL,
    avatar_url      VARCHAR(500),
    bio             TEXT,
    city            VARCHAR(100),
    language        VARCHAR(5) NOT NULL DEFAULT 'en',
    heishi_id       VARCHAR(20) NOT NULL UNIQUE,
    phone_verified  BOOLEAN NOT NULL DEFAULT TRUE,
    wechat_bound    BOOLEAN NOT NULL DEFAULT FALSE,
    alipay_bound    BOOLEAN NOT NULL DEFAULT FALSE,
    identity_verified BOOLEAN NOT NULL DEFAULT FALSE,
    business_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_users_phone ON users (phone);
CREATE INDEX IF NOT EXISTS ix_users_email ON users (email);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          VARCHAR(36) PRIMARY KEY,
    user_id     VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(255) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE TABLE IF NOT EXISTS listings (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id           VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type                VARCHAR(20) NOT NULL DEFAULT 'product',
    title               VARCHAR(200) NOT NULL,
    title_zh            VARCHAR(200),
    description         TEXT NOT NULL DEFAULT '',
    description_zh      TEXT,
    price               DOUBLE PRECISION NOT NULL,
    category_key        VARCHAR(50) NOT NULL,
    tag_key             VARCHAR(50) NOT NULL DEFAULT '',
    condition_key       VARCHAR(50),
    location_label      VARCHAR(100) NOT NULL,
    region_state        VARCHAR(10) NOT NULL DEFAULT 'VIC',
    region_city         VARCHAR(50) NOT NULL DEFAULT 'Melbourne',
    region_area         VARCHAR(50) NOT NULL DEFAULT 'Clayton',
    image_url           VARCHAR(500) NOT NULL,
    images_json         TEXT NOT NULL DEFAULT '[]',
    status              VARCHAR(20) NOT NULL DEFAULT 'active',
    negotiable          BOOLEAN NOT NULL DEFAULT FALSE,
    escrow_supported    BOOLEAN NOT NULL DEFAULT TRUE,
    pickup_methods_json TEXT NOT NULL DEFAULT '["meetup"]',
    service_icon        VARCHAR(30),
    view_count          INTEGER NOT NULL DEFAULT 0,
    favorite_count      INTEGER NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_listings_seller_id ON listings (seller_id);
CREATE INDEX IF NOT EXISTS ix_listings_status ON listings (status);

CREATE TABLE IF NOT EXISTS orders (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id          VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    listing_id        INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    seller_id         VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status            VARCHAR(20) NOT NULL DEFAULT 'pendingPay',
    amount            DOUBLE PRECISION NOT NULL,
    escrow_fee        DOUBLE PRECISION NOT NULL DEFAULT 0,
    delivery_method   VARCHAR(50) NOT NULL DEFAULT 'meetup',
    payment_method_id VARCHAR(36),
    payment_method    VARCHAR(30),
    psp               VARCHAR(20),
    payment_status    VARCHAR(30),
    psp_payment_id    VARCHAR(100),
    psp_transaction_id VARCHAR(100),
    charge_currency   VARCHAR(3) NOT NULL DEFAULT 'aud',
    amount_minor      INTEGER,
    display_amount_cny DOUBLE PRECISION,
    payout_paused     BOOLEAN NOT NULL DEFAULT FALSE,
    payout_status     VARCHAR(30) NOT NULL DEFAULT 'pending',
    payout_provider   VARCHAR(20),
    payout_method_id  VARCHAR(36),
    payout_reference  VARCHAR(100),
    payout_failure_code VARCHAR(50),
    payout_failure_reason TEXT,
    payout_released_at TIMESTAMPTZ,
    payout_failed_at  TIMESTAMPTZ,
    payout_reversed_at TIMESTAMPTZ,
    payout_reversal_reference VARCHAR(100),
    is_abnormal       BOOLEAN NOT NULL DEFAULT FALSE,
    admin_notes       TEXT,
    dispute_status    VARCHAR(30),
    dispute_reason    TEXT,
    dispute_evidence_json TEXT NOT NULL DEFAULT '[]',
    confirmed_at      TIMESTAMPTZ,
    auto_confirm_at   TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_orders_buyer_id ON orders (buyer_id);
CREATE INDEX IF NOT EXISTS ix_orders_listing_id ON orders (listing_id);
CREATE INDEX IF NOT EXISTS ix_orders_status ON orders (status);

-- ============================================================
-- 2. User library
-- ============================================================

CREATE TABLE IF NOT EXISTS favorites (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    listing_id  INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, listing_id)
);

CREATE INDEX IF NOT EXISTS ix_favorites_user_id ON favorites (user_id);
CREATE INDEX IF NOT EXISTS ix_favorites_listing_id ON favorites (listing_id);

CREATE TABLE IF NOT EXISTS view_history (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    listing_id  INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    viewed_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, listing_id)
);

CREATE INDEX IF NOT EXISTS ix_view_history_user_id ON view_history (user_id);
CREATE INDEX IF NOT EXISTS ix_view_history_listing_id ON view_history (listing_id);

CREATE TABLE IF NOT EXISTS follows (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id  VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    followed_id  VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (follower_id, followed_id)
);

CREATE INDEX IF NOT EXISTS ix_follows_follower_id ON follows (follower_id);
CREATE INDEX IF NOT EXISTS ix_follows_followed_id ON follows (followed_id);

CREATE TABLE IF NOT EXISTS coupons (
    id          VARCHAR(36) PRIMARY KEY,
    user_id     VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount      DOUBLE PRECISION NOT NULL,
    description VARCHAR(200) NOT NULL,
    kind        VARCHAR(30),
    expires_at  TIMESTAMPTZ,
    status      VARCHAR(20) NOT NULL DEFAULT 'available'
);

CREATE INDEX IF NOT EXISTS ix_coupons_user_id ON coupons (user_id);

-- ============================================================
-- 3. Messaging
-- ============================================================

CREATE TABLE IF NOT EXISTS conversations (
    id                VARCHAR(36) PRIMARY KEY,
    listing_id        INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    buyer_id          VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    seller_id         VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    last_message_text TEXT,
    last_message_at   TIMESTAMPTZ,
    buyer_unread      INTEGER NOT NULL DEFAULT 0,
    seller_unread     INTEGER NOT NULL DEFAULT 0,
    buyer_read_inbox_at  TIMESTAMPTZ,
    seller_read_inbox_at TIMESTAMPTZ,
    buyer_marked_unread  BOOLEAN NOT NULL DEFAULT FALSE,
    seller_marked_unread BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_conversations_listing_id ON conversations (listing_id);
CREATE INDEX IF NOT EXISTS ix_conversations_buyer_id ON conversations (buyer_id);
CREATE INDEX IF NOT EXISTS ix_conversations_seller_id ON conversations (seller_id);

CREATE TABLE IF NOT EXISTS messages (
    id              VARCHAR(36) PRIMARY KEY,
    conversation_id VARCHAR(36) NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id       VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    text            TEXT NOT NULL,
    sent_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_messages_conversation_id ON messages (conversation_id);

-- ============================================================
-- 4. Profile & settings
-- ============================================================

CREATE TABLE IF NOT EXISTS addresses (
    id           VARCHAR(36) PRIMARY KEY,
    user_id      VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    label        VARCHAR(100) NOT NULL,
    area         VARCHAR(100) NOT NULL,
    meetup_spot  VARCHAR(200),
    is_default   BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS ix_addresses_user_id ON addresses (user_id);

CREATE TABLE IF NOT EXISTS payment_methods (
    id                        VARCHAR(36) PRIMARY KEY,
    user_id                   VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type                      VARCHAR(20) NOT NULL,
    label                     VARCHAR(100) NOT NULL,
    last4                     VARCHAR(4),
    is_default                BOOLEAN NOT NULL DEFAULT FALSE,
    stripe_payment_method_id  VARCHAR(100),
    brand                     VARCHAR(20),
    exp_month                 INTEGER,
    exp_year                  INTEGER
);

CREATE INDEX IF NOT EXISTS ix_payment_methods_user_id ON payment_methods (user_id);

CREATE TABLE IF NOT EXISTS payout_methods (
    id                          VARCHAR(36) PRIMARY KEY,
    user_id                     VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type                        VARCHAR(20) NOT NULL,
    label                       VARCHAR(100) NOT NULL,
    last4                       VARCHAR(4),
    account_ref                 VARCHAR(255),
    is_default                  BOOLEAN NOT NULL DEFAULT FALSE,
    stripe_external_account_id  VARCHAR(100),
    payouts_enabled             BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS ix_payout_methods_user_id ON payout_methods (user_id);

CREATE TABLE IF NOT EXISTS user_settings (
    user_id           VARCHAR(36) PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    intent_alerts     BOOLEAN NOT NULL DEFAULT TRUE,
    chat_messages     BOOLEAN NOT NULL DEFAULT TRUE,
    review_results    BOOLEAN NOT NULL DEFAULT TRUE,
    marketing         BOOLEAN NOT NULL DEFAULT FALSE,
    find_by_phone     BOOLEAN NOT NULL DEFAULT TRUE,
    show_wechat_badge BOOLEAN NOT NULL DEFAULT FALSE,
    personalization   BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================================
-- 5. Safety & reviews
-- ============================================================

CREATE TABLE IF NOT EXISTS safety_reports (
    id          VARCHAR(36) PRIMARY KEY,
    reporter_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_type VARCHAR(20) NOT NULL,
    target_id   VARCHAR(50) NOT NULL,
    reason      VARCHAR(100) NOT NULL,
    details     TEXT,
    status      VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_safety_reports_reporter_id ON safety_reports (reporter_id);

CREATE TABLE IF NOT EXISTS blocklist (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id  VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    blocked_id  VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (blocker_id, blocked_id)
);

CREATE INDEX IF NOT EXISTS ix_blocklist_blocker_id ON blocklist (blocker_id);
CREATE INDEX IF NOT EXISTS ix_blocklist_blocked_id ON blocklist (blocked_id);

CREATE TABLE IF NOT EXISTS system_notifications (
    id         VARCHAR(36) PRIMARY KEY,
    user_id    VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title       VARCHAR(200) NOT NULL,
    body        TEXT NOT NULL,
    unread      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_system_notifications_user_id ON system_notifications (user_id);

CREATE TABLE IF NOT EXISTS reviews (
    id          VARCHAR(36) PRIMARY KEY,
    order_id    INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    reviewer_id VARCHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rating      INTEGER NOT NULL,
    comment     TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (order_id, reviewer_id)
);

-- ============================================================
-- Done — 18 tables created
-- ============================================================
